version: '3'

volumes:
  postgres_db_vol:
  pgadmin-data:

services:

  db_postgres:
    image: postgres:16.4
    container_name: postgres_db_container
    env_file:
      - .env
    volumes:
      - postgres_db_vol:/var/lib/postgresql/data
    restart: unless-stopped

  club_pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:8.6
    depends_on:
      - db_postgres
    env_file:
      - .env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5051:80"
    restart: unless-stopped

  app:
    build: ./
    depends_on:
      - db_postgres
    env_file:
      - .env
    environment:
      - TOKEN
      - DEBUG
    volumes:
      - ./bot/locales:/app/bot/locales
      - ./alembic:/app/alembic
    restart: unless-stopped
